sudo: required

services:
  - docker

script:
  - docker build -t kmcgill88/k-plex:latest .
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push kmcgill88/k-plex:latest;
    fi
